USE UD3;
CREATE DATABASE IF NOT EXISTS UD3 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS ACT2;
CREATE TABLE ACT2 (
campo1 TINYINT UNSIGNED PRIMARY KEY,
campo2 DECIMAL(3, 2),
campo3 VARCHAR(4),
campo4 DATE,
campo5 CHAR(1),
campo6 ENUM('hombre', 'mujer')
);

DROP TABLE IF EXISTS usuario;
CREATE TABLE usuario (
	id INT PRIMARY KEY AUTO_INCREMENT,
    dni CHAR(9) UNIQUE,
	nombre VARCHAR(9) UNIQUE,
    edad TINYINT CHECK (edad >= 0 AND edad < 120) DEFAULT 20
)
